//
// DO NOT EDIT MANUALLY
// Generated by scripts/generate-vcl.ts from src/utils/cachePolicy.ts
//
// This file mirrors the canonical cache policy defined in the backend.
// Run `npm run docs:vcl` to regenerate.
//

sub vcl_fetch {
  // ----------------------------------------------------------------
  // Edge Cache Rules — generated from cache policy matrix
  // ----------------------------------------------------------------

  // public-attestations-active: Active (non-revoked) public attestation by hash identifier
  // Cache-Control: public, max-age=60, stale-while-revalidate=60, stale-if-error=86400
  if (req.method == "GET" && req.url ~ "^/api/v1/public/attestations/[^/]+(\?.*)?$") {
    set beresp.ttl = 60s;
    set beresp.stale_while_revalidate = 60s;
    set beresp.stale_if_error = 86400s;
    set beresp.http.Cache-Control = "public, max-age=60, stale-while-revalidate=60, stale-if-error=86400";
    set beresp.http.Vary = "Accept, X-API-Version, Accept-Version";
  }

  // public-attestations-revoked: Revoked public attestation — shorter TTL so revocation propagates quickly
  // Cache-Control: public, max-age=15, stale-while-revalidate=60, stale-if-error=3600
  if (req.method == "GET" && req.url ~ "^/api/v1/public/attestations/[^/]+(\?.*)?$") {
    set beresp.ttl = 15s;
    set beresp.stale_while_revalidate = 60s;
    set beresp.stale_if_error = 3600s;
    set beresp.http.Cache-Control = "public, max-age=15, stale-while-revalidate=60, stale-if-error=3600";
    set beresp.http.Vary = "Accept, X-API-Version, Accept-Version";
  }

  // webhook-egress-ips: Signed manifest of NAT egress IPs used for outbound webhooks
  // Cache-Control: public, max-age=3600, stale-while-revalidate=60, stale-if-error=86400
  if (req.method == "GET" && req.url ~ "^/.well-known/webhook-egress-ips(\?.*)?$") {
    set beresp.ttl = 3600s;
    set beresp.stale_while_revalidate = 60s;
    set beresp.stale_if_error = 86400s;
    set beresp.http.Cache-Control = "public, max-age=3600, stale-while-revalidate=60, stale-if-error=86400";
    set beresp.http.Vary = "Accept, X-API-Version, Accept-Version";
  }

  // jwks: JSON Web Key Set for JWT signature verification
  // Cache-Control: public, max-age=300, stale-while-revalidate=60, stale-if-error=86400
  if (req.method == "GET" && req.url ~ "^/.well-known/jwks.json(\?.*)?$") {
    set beresp.ttl = 300s;
    set beresp.stale_while_revalidate = 60s;
    set beresp.stale_if_error = 86400s;
    set beresp.http.Cache-Control = "public, max-age=300, stale-while-revalidate=60, stale-if-error=86400";
    set beresp.http.Vary = "Accept, X-API-Version, Accept-Version";
  }

  // Default: respect origin Cache-Control (if any)
  if (!beresp.http.Cache-Control) {
    set beresp.ttl = 0s;
    set beresp.stale_while_revalidate = 0s;
    set beresp.stale_if_error = 0s;
  }
}

sub vcl_deliver {
  // ----------------------------------------------------------------
  // Delivery-time adjustments
  // ----------------------------------------------------------------

  // public-attestations-revoked
  if (req.method == "GET" && req.url ~ "^/api/v1/public/attestations/[^/]+(\?.*)?$") {
    unset resp.http.ETag;
  }

  // webhook-egress-ips
  if (req.method == "GET" && req.url ~ "^/.well-known/webhook-egress-ips(\?.*)?$") {
    unset resp.http.ETag;
  }

  // Remove Server header for security
  unset resp.http.Server;
}