/**
 * @module tokenHash
 *
 * Secure token hashing utilities for authentication tokens stored at rest.
 *
 * Security rationale
 * ──────────────────
 * Raw reset tokens are high-entropy secrets (32 random bytes, 256 bits of
 * entropy) — functionally equivalent to passwords.  Storing them in plaintext
 * means a single database read (e.g. via a SQL injection, a stolen backup, or
 * an accidental log flush) is enough to mass-exploit every active reset request.
 *
 * By storing only the SHA-256 digest of the token we decouple the lookup key
 * from the secret itself:
 *
 *   • Database contains: SHA-256(token)  — useless to an attacker without
 *     performing 2^256 brute-force work per record.
 *   • Application uses:  raw token       — emailed to the user, compared by
 *     hashing the incoming value before the DB query.
 *   • Logs contain:      token[0..7]     — a short prefix for correlation,
 *     never enough to reconstruct the full token or its hash.
 *
 * Why SHA-256 and not bcrypt?
 * ───────────────────────────
 * Reset tokens already have 256 bits of CSPRNG entropy — far exceeding any
 * realistic brute-force budget.  bcrypt's cost factor is designed to slow
 * down low-entropy inputs (passwords); applying it to a random 32-byte token
 * adds latency and complexity with no measurable security benefit.  SHA-256
 * is collision-resistant, available in the Node.js standard library, and
 * completes in microseconds.
 */

import { createHash } from 'node:crypto'

/**
 * Compute the SHA-256 digest of a raw hexadecimal reset token.
 *
 * @param rawToken - The 64-character hex string generated by `crypto.randomBytes(32)`.
 * @returns        - A 64-character lowercase hex string (SHA-256 digest).
 *
 * @example
 * ```ts
 * const hash = hashResetToken(rawToken)
 * // → "e3b0c44298fc1c14..." (64 hex chars)
 * ```
 */
export function hashResetToken(rawToken: string): string {
  return createHash('sha256').update(rawToken, 'utf8').digest('hex')
}

/**
 * Return the first `length` characters of a raw token for use in audit logs.
 *
 * Only the prefix is logged — never the full token or its hash — to allow
 * log correlation without leaking the secret.
 *
 * @param rawToken - The full raw token string.
 * @param length   - Number of leading characters to expose (default: 8).
 */
export function tokenLogPrefix(rawToken: string, length = 8): string {
  return rawToken.slice(0, length)
}
