/**
 * Fastly VCL Generator
 *
 * Reads the canonical cache policy matrix from src/utils/cachePolicy.ts and
 * emits a Fastly VCL snippet (or full `vcl_fetch` / `vcl_deliver` subroutines)
 * that mirrors the backend's Cache-Control headers at the Fastly edge.
 *
 * Usage:
 *   npx tsx scripts/generate-vcl.ts
 *   npx tsx scripts/generate-vcl.ts --check   # verify generated VCL matches committed file
 *
 * The backend policy is always the canonical source of truth.  If the generated
 * VCL differs from the committed ops/fastly/edge-cache.vcl file, run this
 * script and commit the updated output.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  CACHE_POLICIES,
  formatCacheControl,
  type CachePolicyEntry,
} from '../src/utils/cachePolicy.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const VCL_OUT_PATH = path.resolve(__dirname, '../ops/fastly/edge-cache.vcl');

// ---------------------------------------------------------------------------
// VCL Generation
// ---------------------------------------------------------------------------

/**
 * Convert an Express-style route path (:param tokens) to a Fastly VCL
 * regex-compatible pattern for use in `req.url` matching.
 *
 * Fastly VCL uses POSIX extended regular expressions via `re-match`.
 * We translate :param to `[^/]+` and anchor at start.
 */
function routeToVclPattern(expressPath: string): string {
  return expressPath.replace(/:[\w]+/g, '[^/]+');
}

/**
 * Generate the complete VCL content for the `vcl_fetch` subroutine.
 */
export function generateVcl(): string {
  const lines: string[] = [];

  // ---- Header ----
  lines.push('//');
  lines.push('// DO NOT EDIT MANUALLY');
  lines.push('// Generated by scripts/generate-vcl.ts from src/utils/cachePolicy.ts');
  lines.push('//');
  lines.push('// This file mirrors the canonical cache policy defined in the backend.');
  lines.push('// Run `npm run docs:vcl` to regenerate.');
  lines.push('//');
  lines.push('');

  lines.push('sub vcl_fetch {');
  lines.push('  // ----------------------------------------------------------------');
  lines.push('  // Edge Cache Rules — generated from cache policy matrix');
  lines.push('  // ----------------------------------------------------------------');
  lines.push('');

  for (const policy of CACHE_POLICIES) {
    const vclPattern = routeToVclPattern(policy.path);
    const cacheControl = formatCacheControl(policy.directives);
    const ifExpression = buildIfExpression(policy, vclPattern);

    lines.push(`  // ${policy.name}: ${policy.description}`);
    lines.push(`  // Cache-Control: ${cacheControl}`);
    lines.push(`  if (${ifExpression}) {`);

    // Set beresp TTLs
    lines.push(`    set beresp.ttl = ${policy.directives.maxAge}s;`);
    lines.push(
      `    set beresp.stale_while_revalidate = ${policy.directives.staleWhileRevalidate}s;`,
    );
    lines.push(
      `    set beresp.stale_if_error = ${policy.directives.staleIfError}s;`,
    );

    // Set Cache-Control on the response so downstream caches see it too
    lines.push(`    set beresp.http.Cache-Control = "${cacheControl}";`);

    // Apply Vary header to prevent cache fragmentation
    lines.push('    set beresp.http.Vary = "Accept, X-API-Version, Accept-Version";');

    // Custom VCL snippets per policy (if any)
    if (policy.customVcl && policy.customVcl.length > 0) {
      for (const snippet of policy.customVcl) {
        lines.push(`    ${snippet}`);
      }
    }

    lines.push('  }');
    lines.push('');
  }

  // ---- Fallback ----
  lines.push('  // Default: respect origin Cache-Control (if any)');
  lines.push('  if (!beresp.http.Cache-Control) {');
  lines.push('    set beresp.ttl = 0s;');
  lines.push('    set beresp.stale_while_revalidate = 0s;');
  lines.push('    set beresp.stale_if_error = 0s;');
  lines.push('  }');
  lines.push('}');

  // ---- vcl_deliver subroutine ----
  lines.push('');
  lines.push('sub vcl_deliver {');
  lines.push('  // ----------------------------------------------------------------');
  lines.push('  // Delivery-time adjustments');
  lines.push('  // ----------------------------------------------------------------');
  lines.push('');

  for (const policy of CACHE_POLICIES) {
    const vclPattern = routeToVclPattern(policy.path);
    const ifExpression = buildIfExpression(policy, vclPattern);
    const adjustments: string[] = [];

    // Remove ETag for responses that don't support it (keeps VCL clean)
    if (!policy.supportsEtag) {
      adjustments.push('    unset resp.http.ETag;');
    }

    if (adjustments.length > 0) {
      lines.push(`  // ${policy.name}`);
      lines.push(`  if (${ifExpression}) {`);
      for (const adj of adjustments) {
        lines.push(adj);
      }
      lines.push('  }');
      lines.push('');
    }
  }

  lines.push('  // Remove Server header for security');
  lines.push('  unset resp.http.Server;');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Build the VCL if-condition for a cache policy entry.
 */
function buildIfExpression(policy: CachePolicyEntry, vclPattern: string): string {
  const parts: string[] = [];

  // Match on HTTP method
  if (policy.methods.length === 1) {
    parts.push(`req.method == "${policy.methods[0]}"`);
  } else {
    const methodExpr = policy.methods.map((m) => `req.method == "${m}"`).join(' || ');
    parts.push(`(${methodExpr})`);
  }

  // Match on URL pattern
  parts.push(`req.url ~ "^${vclPattern}(\\?.*)?$"`);

  return parts.join(' && ');
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

export function main() {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');

  const vcl = generateVcl();

  if (checkOnly) {
    // Compare generated VCL with the committed file
    let existing = '';
    try {
      existing = fs.readFileSync(VCL_OUT_PATH, 'utf-8');
    } catch {
      console.error(`❌ VCL file not found at ${VCL_OUT_PATH}. Run 'npm run docs:vcl' first.`);
      process.exit(1);
    }

    if (vcl.trim() === existing.trim()) {
      console.log('✅ Generated VCL matches committed ops/fastly/edge-cache.vcl');
      process.exit(0);
    } else {
      console.error(
        '❌ Generated VCL differs from committed ops/fastly/edge-cache.vcl. Run \'npm run docs:vcl\' to regenerate.',
      );
      process.exit(1);
    }
  }

  // Ensure output directory exists
  const outDir = path.dirname(VCL_OUT_PATH);
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  fs.writeFileSync(VCL_OUT_PATH, vcl, 'utf-8');
  console.log(`✅ Generated Fastly VCL at ${VCL_OUT_PATH}`);
  console.log(`   Policies emitted: ${CACHE_POLICIES.length}`);
  for (const policy of CACHE_POLICIES) {
    const cc = formatCacheControl(policy.directives);
    console.log(`   • ${policy.name}: ${policy.path} → ${cc}`);
  }
}

if (process.argv[1] === __filename) {
  main();
}
