apiVersion: v1
kind: Service
metadata:
  name: {{ include "veritasor.fullname" . }}
  labels:
    {{- include "veritasor.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.metricsPort | quote }}
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "veritasor.selectorLabels" . | nindent 4 }}
